iteasykit/config/routes.rb
Iteasykit::Engine.routes.draw do

  #filter :pagination, :uuid
  filter :locale
  mount Ckeditor::Engine => '/ckeditor'
  resources :forms
  root :to => 'entities#index'
  resources :taxonomies
  resources :entities
  devise_for :users, class_name: "Iteasykit::User", module: :devise, :controllers => { :registrations => :registrations }
  namespace :admin do
    resources :taxonomies
    resources :fcis
    resources :entities
    resources :seomores
    resources :forms
    resources :cells
    resources :menus
    resources :menu_items do
      post :sort, on: :collection
    end
    resources :blocks do
      post :sort, on: :collection
    end
    resources :entity_types

  end
  resources :fci_images
  get 'admin/dashboard' => 'admin/page#dashboard', as: 'admin_dashboard'
  get 'admin/help' => 'admin/page#help', as: 'admin_help'
  get 'admin/entity_types/:id/fields' => 'admin/entity_types#fields', as: 'admin_entity_type_fields'
  get 'admin/entity/:id/custom_fields' => 'admin/entities#custom_fields', as: 'admin_entity_custom_fields'
  get 'admin/blocks/:id/custom_fields' => 'admin/blocks#custom_fields', as: 'admin_block_custom_fields'
  get 'admin/taxonomy/:id/custom_fields' => 'admin/taxonomies#custom_fields', as: 'admin_taxonomy_custom_fields'
  get 'admin/fcis/:id/destroy_fields' => 'admin/fcis#destroy_fields', as: 'admin_fci_destroy_fields'


  Iteasykit::DynamicRouter.load
  

end

iteasykit/app/models/iteasykit/cell.rb
module Iteasykit
  class Cell < ApplicationRecord
    belongs_to :iteasykit_entity_type, class_name: "Iteasykit::EntityType"
    has_many :fcis, as: :fciable
    has_many :iteasykit_rel_cells, class_name: "Iteasykit::RelCell", foreign_key: :iteasykit_cell_id, dependent: :destroy
    #before_destroy :destroy_field

    Iteasykit::EntityType.where(rel_model: 'Cell').includes(:fcis).each do |et|
      et.fcis.each do |fci|
        has_many fci.machine_name.pluralize.to_sym, -> {where(fieldable_type: 'Iteasykit::Cell', iteasykit_fci_id: fci.id)}, class_name: "Iteasykit::Fci#{fci.type_fci.camelize}", foreign_key: :fieldable_id
      end
    end

    default_scope { order("position ASC") }


    def field(name)
      fci = Iteasykit::Fci.find_by_machine_name(name)
      if fci
        m = ('Iteasykit::Fci'+fci.type_fci.camelize).constantize
        mf = m.find_by(iteasykit_fci_id: fci.id, fieldable_type: 'Iteasykit::Cell', fieldable_id: id)
        if mf
          if m.class_name == "IteasykitFciImage"
            mf.file
          else
            if mf.value.class == Integer
              mfv = mf.value
            else
              mfv = mf.value.html_safe
            end
          end
        end
      end
    end

    def field_name(name)
      fci = Iteasykit::Fci.find_by_machine_name(name)
      fci.name.html_safe if fci
    end

    def title
      if iteasykit_entity_type.id_title_fci.present?
        fci = Iteasykit::Fci.find(iteasykit_entity_type.id_title_fci)
        mf = FciString.find_by(iteasykit_fci_id: fci.id, fieldable_type: 'Iteasykit::Cell', fieldable_id: id)
        if mf
          mf.value.html_safe
        end
      end
    end

    def geod
      if iteasykit_entity_type_id == 20
        if self.coordinates20s.present?
          g = self.coordinates20s.first
          if self.adres20s.present?
            a = self.adres20s.first
            p a.value
            ga = Geocoder.coordinates(a.value)
            p ga
            g.update!(value: ga.to_s.gsub('[','').gsub(']',''))
          end
        else
          if self.adres20s.present?
            a = self.adres20s.first
            p a.value
            ga = Geocoder.coordinates(a.value)
            p ga
            Iteasykit::FciString.create(iteasykit_fci_id: 279, fieldable_type: "Iteasykit::Cell", fieldable_id: self.id, value: ga.to_s.gsub('[','').gsub(']',''))
          end

        end
      end
    end

    def geoddee
      if iteasykit_entity_type_id == 19
        if self.coordinates19s.present?
          g = self.coordinates19s.first
          if self.geodannye19s.present?
            a = self.geodannye19s.first
            p a.value
            ga = Geocoder.coordinates(a.value)
            p ga
            g.update!(value: ga.to_s.gsub('[','').gsub(']',''))
          end
        else
          if self.geodannye19s.present?
            a = self.geodannye19s.first
            p a.value
            ga = Geocoder.coordinates(a.value)
            p ga
            Iteasykit::FciString.create(iteasykit_fci_id: 280, fieldable_type: "Iteasykit::Cell", fieldable_id: self.id, value: ga.to_s.gsub('[','').gsub(']',''))
          end

        end
      end
    end


  end
end

iteasykit/app/controllers/iteasykit/admin/cells_controller.rb
require_dependency "iteasykit/application_controller"

module Iteasykit
  class  Admin::CellsController < Admin::AdminController
    before_action :set_cell, only: [:show, :edit, :update, :destroy]

    # GET /cells
    def index
      @cells = Cell.all
    end

    # GET /cells/1
    def show
    end

    # GET /cells/new
    def new
      @entity_type = Iteasykit::EntityType.find(params[:entity_type])
      @cell = Cell.new
      @group_list = Iteasykit::Cell.all.map{|e| e.group}.uniq
    end

    # GET /cells/1/edit
    def edit
    end

    # POST /cells
    def create
      @cell = Cell.new(cell_params)

      if @cell.save
        if params[:object_relable].present?
          Iteasykit::RelCell.create(iteasykit_cell_id: @cell.id, relable_type: params[:object_relable], relable_id: params[:object_relable_id])
        end
        fci_saver(@cell, params)
        if params[:object_relable].present?
          redirect_back(fallback_location: edit_admin_cell_url(@cell))
        else
          redirect_to edit_admin_cell_url(@cell), notice: 'Cell was successfully created.'
        end
      else
        render :new
      end
    end

    # PATCH/PUT /cells/1
    def update
      if @cell.update(cell_params)
        fci_saver(@cell, params)
        if params[:object_relable].present?
          redirect_back(fallback_location: edit_admin_cell_url(@cell))
        else
          redirect_to edit_admin_cell_url(@cell), notice: 'Cell was successfully updated.'
        end
      else
        render :edit
      end
    end

    # DELETE /cells/1
    def destroy
      @cell.destroy
      redirect_back(fallback_location: edit_admin_cell_url(@cell))
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_cell
        @cell = Cell.find(params[:id])
        @entity_type = @cell.iteasykit_entity_type
        @group_list = Iteasykit::Cell.all.map{|e| e.group}.uniq
      end

      # Only allow a trusted parameter "white list" through.
      def cell_params
        params.require(:cell).permit(:iteasykit_entity_type_id, :active, :sticky, :position, :group, :machine_name)
      end
  end
end

iteasykit/app/helpers/iteasykit/cells_helper.rb
module Iteasykit
  module CellsHelper

    def relscells(obj,mid)
      obj.iteasykit_cells.where(iteasykit_entity_type_id: mid).page(params[:page]).per(6)
    end

  end
end

iteasykit/app/views/iteasykit/admin/cells/_form.html.erb
<div class="row">
<%= form_with(model: [:admin, cell], local: true, multipart:true) do |form| %>
  <% if cell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cell.errors.count, "error") %> prohibited this cell from being saved:</h2>

      <ul>
      <% cell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="col-md-8">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('field_and_objects') %></h5>
        </div>

        <div class="content">
          <%= render 'iteasykit/shared/fields/field_list', locals: [@entity_type, @object = @cell] %>

        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('settings') %></h5>
        </div>

        <div class="content">
          <div class="form-group">
            <label class="control-label"><%= t('entity_type') %></label>
            <%= form.select(:iteasykit_entity_type_id, Iteasykit::EntityType.where(rel_model: 'Cell').map {|et| [et.name, et.id]},
                            {include_blank: false}, class: "form-control input-sm input-warning") %>
            <span class="help-block"><small><%= t('no_edit') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('machine_name') %></label>
            <%= form.text_field :machine_name, class: "form-control input-sm" %>
            <span class="help-block"><small><%= t('machine_name_for_theme') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('group') %></label>
            <%= form.text_field :group, class: "form-control input-sm" %>
            <span class="help-block"><small><%= t('group_cells_available') %> <%= @group_list.join(', ') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('position') %></label>
            <%= form.text_field :position, class: "form-control input-sm" %>
            <span class="help-block"><small><%= t('position_cells') %></small></span>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label text-color">
                  <%= t('active') %>
                  <%= form.check_box :active, class: "toggle toggle-success" %>
                  <i></i>
                </label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label text-color">

                  <%= t('sticky') %>
                  <%= form.check_box :sticky, class: "toggle toggle-success" %>
                  <i></i>
                </label>
              </div>
            </div>
          </div>


        </div>
      </div>
      </div>
    <div class="actions"  style="position: fixed;bottom: 0px;right: 0px;" >
      <%= form.submit t('save'), class: "btn-success btn-lg"%>
    </div>
<% end %>
</div>

iteasykit/app/views/iteasykit/admin/cells/_list_objects.html.erb
<table class="table table-bordered table-hover table-striped">
  <thead>
  <tr>
    <th><%= t('id') %></th>
    <th><%= t('active') %></th>
    <th><%= t('sticky') %></th>
    <th><%= t('position') %></th>
    <th><%= t('group') %></th>
    <th><%= t('machine_name') %></th>
    <th><%= t('action') %></th>
  </tr>
  </thead>

  <tbody>
  <% @object_list.each do |cell| %>
    <tr>
      <td><%= cell.id %></td>
      <td><i class="zmdi zmdi-<%= cell.active ? 'check' : 'close' %>"></i></td>
      <td><i class="zmdi zmdi-<%= cell.sticky ? 'check' : 'close' %>"></i></td>
      <td><%= cell.position %></td>
      <td><%= cell.group %></td>
      <td><%= cell.machine_name %></td>
      <td class="text-center">
        <%= link_to '<i class="zmdi zmdi-edit"></i>'.html_safe, edit_admin_cell_path(cell), class: "btn btn-success raised icon waves-effect" %>
        <%= link_to '<i class="zmdi zmdi-delete"></i>'.html_safe, [:admin, cell], class: "btn btn-danger raised icon waves-effect", method: :delete,
                    data: {confirm: 'Are you sure?'} %>     </td>

    </tr>
  <% end %>
  </tbody>
</table>

iteasykit/app/views/iteasykit/admin/cells/_popup_form.html.erb
<% @entity_type = @cell.iteasykit_entity_type unless @cell.new_record? %><div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title"><%= t('cell') %> - <%= @entity_type.name %></h4>
    </div>
    <%= form_with(model: [:admin, @cell], local: true, multipart:true) do |form| %>
    <div class="modal-body">
      <div class="row">

  <% if @cell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cell.errors.count, "error") %> prohibited this cell from being saved:</h2>

      <ul>
      <% @cell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="col-md-8">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('field_and_objects') %></h5>
        </div>

        <div class="content">
          <%= render 'iteasykit/shared/fields/field_list', locals: [@entity_type, @object = @cell] %>

        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('settings') %></h5>
        </div>

        <div class="content">
          <div class="form-group">
            <label class="control-label"><%= t('entity_type') %></label>
            <%= form.select(:iteasykit_entity_type_id, options_for_select(Iteasykit::EntityType.where(rel_model: 'Cell').map {|et| [et.name, et.id]}, :selected =>  @entity_type.id),
                            {include_blank: false}, class: "form-control input-sm input-warning") %>
            <span class="help-block"><small><%= t('no_edit') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('machine_name') %></label>
            <%= form.text_field :machine_name, class: "form-control input-sm" %>
            <span class="help-block"><small><%= t('machine_name_for_theme') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('group') %></label>
            <%= form.text_field :group, class: "form-control input-sm" %>
            <span class="help-block"><small><%= t('group_cells_available') %> <%= Iteasykit::Cell.all.map{|e| e.group}.uniq.join(', ') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('position') %></label>
            <%= form.text_field :position, class: "form-control input-sm" %>
            <span class="help-block"><small><%= t('position_cells') %></small></span>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label text-color">
                  <%= t('active') %>
                  <%= form.check_box :active, class: "toggle toggle-success" %>
                  <i></i>
                </label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label text-color">

                  <%= t('sticky') %>
                  <%= form.check_box :sticky, class: "toggle toggle-success" %>
                  <i></i>
                </label>
              </div>
            </div>
          </div>


        </div>
      </div>
      </div>

</div>
    </div>
      <%= hidden_field_tag 'object_relable', @objectrel.class.name %>
      <%= hidden_field_tag 'object_relable_id', @objectrel.id %>
    <div class="modal-footer">
      <%= form.submit t('save'), class: "btn-info btn-lg" %>
      <button type="button" class="btn btn-lg btn-default m-b-5" data-dismiss="modal"><%= t('close') %></button>
    </div>
    <% end %>
  </div>
</div>

iteasykit/app/views/iteasykit/admin/cells/_rel_list_objects.html.erb
<%= paginate @object_list %>
<table class="table table-bordered table-hover table-striped">
  <thead>
  <tr>
    <th><%= t('id:') %></th>
    <th><%= t('title') %></th>
    <th><%= t('active') %></th>
    <th><%= t('sticky') %></th>
    <th><%= t('entity_type') %></th>
    <th><%= t('group') %></th>
    <th><%= t('machine_name') %></th>
    <th><%= t('action') %></th>
  </tr>
  </thead>

  <tbody>
  <% @object_list.each do |rel| %>
  <% cell = rel.iteasykit_cell %>
    <tr>
      <td><%= cell.id %></td>
      <td><%= cell.title %></td>
      <td><i class="zmdi zmdi-<%= cell.active ? 'check' : 'close' %>"></i></td>
      <td><i class="zmdi zmdi-<%= cell.sticky ? 'check' : 'close' %>"></i></td>
      <td><%= cell.iteasykit_entity_type.name if cell.iteasykit_entity_type %></td>
      <td><%= cell.group %></td>
      <td><%= cell.machine_name %></td>
      <td class="text-center">
        <%= link_to '<i class="zmdi zmdi-edit"></i>'.html_safe, "", class: "btn btn-success raised icon waves-effect",
                    'data-toggle'=>"modal", 'data-target'=>"#modal-large#{cell.id}" %>
        <%= link_to '<i class="zmdi zmdi-delete"></i>'.html_safe, [:admin, cell], class: "btn btn-danger raised icon waves-effect", method: :delete,
                    data: {confirm: 'Are you sure?'} %>     </td>

    </tr>
    <div class="modal fade" id="modal-large<%=cell.id %>" role="dialog" aria-hidden="true">
      <%= render 'iteasykit/admin/cells/popup_form', locals: [@cell=cell] %>
    </div>
  <% end %>
  </tbody>
</table>
<%= paginate @object_list %>

iteasykit/app/views/iteasykit/admin/cells/edit.html.erb
<% content_for :entity_title do %><%= t('editing') %> - <%= @entity_type.name %>
<% end %>
<% content_for :pull_right do %>
  <%= link_to '<i class="zmdi zmdi-long-arrow-return zmdi-hc-fw"></i>'.html_safe, admin_entity_type_url(@entity_type) %>
<% end %>
<%= render 'iteasykit/shared/admin/type_tabs', locals: [@obj_current = @cell, @cfield = false, @only_id = true] %>
<%= render 'form', cell: @cell %>

iteasykit/app/views/iteasykit/admin/cells/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cells</h1>

<table>
  <thead>
    <tr>
      <th>Iteasykit entity type</th>
      <th>Active</th>
      <th>Sticky</th>
      <th>Position</th>
      <th>Group</th>
      <th>Machine name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cells.each do |cell| %>
      <tr>
        <td><%= cell.iteasykit_entity_type %></td>
        <td><%= cell.active %></td>
        <td><%= cell.sticky %></td>
        <td><%= cell.position %></td>
        <td><%= cell.group %></td>
        <td><%= cell.machine_name %></td>
        <td><%= link_to 'Show', [:admin, cell] %></td>
        <td><%= link_to 'Edit', edit_admin_cell_path(cell) %></td>
        <td><%= link_to 'Destroy', [:admin, cell], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cell', new_admin_cell_path %>

iteasykit/app/views/iteasykit/admin/cells/new.html.erb
<% content_for :entity_title do %><%= t('add_new_cell') %> - <%= @entity_type.name %>
<% end %>
<% content_for :pull_right do %>
  <%= link_to '<i class="zmdi zmdi-long-arrow-return zmdi-hc-fw"></i>'.html_safe, admin_cells_url %>
<% end %>

<%= render 'iteasykit/shared/admin/type_tabs', locals: [@obj_current = @form] %>
<%= render 'form', cell: @cell %>

iteasykit/app/views/iteasykit/admin/cells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Iteasykit entity type:</strong>
  <%= @cell.iteasykit_entity_type %>
</p>

<p>
  <strong>Active:</strong>
  <%= @cell.active %>
</p>

<p>
  <strong>Sticky:</strong>
  <%= @cell.sticky %>
</p>

<p>
  <strong>Position:</strong>
  <%= @cell.position %>
</p>

<p>
  <strong>Group:</strong>
  <%= @cell.group %>
</p>

<p>
  <strong>Machine name:</strong>
  <%= @cell.machine_name %>
</p>

<%= link_to 'Edit', edit_cell_path(@cell) %> |
<%= link_to 'Back', cells_path %>