iteasykit/config/routes.rb
Iteasykit::Engine.routes.draw do

  #filter :pagination, :uuid
  filter :locale
  mount Ckeditor::Engine => '/ckeditor'
  resources :forms
  root :to => 'entities#index'
  resources :taxonomies
  resources :entities
  devise_for :users, class_name: "Iteasykit::User", module: :devise, :controllers => { :registrations => :registrations }
  namespace :admin do
    resources :taxonomies
    resources :fcis
    resources :entities
    resources :seomores
    resources :forms
    resources :cells
    resources :menus
    resources :menu_items do
      post :sort, on: :collection
    end
    resources :blocks do
      post :sort, on: :collection
    end
    resources :entity_types

  end
  resources :fci_images
  get 'admin/dashboard' => 'admin/page#dashboard', as: 'admin_dashboard'
  get 'admin/help' => 'admin/page#help', as: 'admin_help'
  get 'admin/entity_types/:id/fields' => 'admin/entity_types#fields', as: 'admin_entity_type_fields'
  get 'admin/entity/:id/custom_fields' => 'admin/entities#custom_fields', as: 'admin_entity_custom_fields'
  get 'admin/blocks/:id/custom_fields' => 'admin/blocks#custom_fields', as: 'admin_block_custom_fields'
  get 'admin/taxonomy/:id/custom_fields' => 'admin/taxonomies#custom_fields', as: 'admin_taxonomy_custom_fields'
  get 'admin/fcis/:id/destroy_fields' => 'admin/fcis#destroy_fields', as: 'admin_fci_destroy_fields'


  Iteasykit::DynamicRouter.load
  

end

iteasykit/app/models/iteasykit/block.rb
module Iteasykit
  class Block < ApplicationRecord
    belongs_to :iteasykit_entity_type, class_name: "Iteasykit::EntityType", optional: true
    translates :admin_name, :description_admin
    has_many :fcis, as: :fciable, class_name: "Iteasykit::Fci", foreign_key: :fciable_id
    has_many :rel_cells, as: :relable, class_name: "Iteasykit::RelCell", foreign_key: :relable_id

    default_scope { order("position ASC") }

    def field(name)
      fci = Iteasykit::Fci.find_by_machine_name(name)
      if fci
        m = ('Iteasykit::Fci'+fci.type_fci.camelize).constantize
        mf = m.find_by(iteasykit_fci_id: fci.id, fieldable_type: 'Iteasykit::Block', fieldable_id: id)
        if mf
          if m.class_name == "IteasykitFciImage"
            mf.file
          else
            if mf.value.class == Integer
              mfv = mf.value
            else
              mfv = mf.value.html_safe
            end
          end
        end
      end
    end

    def title
      if iteasykit_entity_type.present?
        if iteasykit_entity_type.id_title_fci.present?
          fci = Iteasykit::Fci.find(iteasykit_entity_type.id_title_fci)
          mf = FciString.find_by(iteasykit_fci_id: fci.id, fieldable_type: 'Iteasykit::Block', fieldable_id: id)
          if mf
            mf.value.html_safe
          end
        end
      end
    end

    def cells(mid)
      rel_cells.joins(:iteasykit_cell).where(iteasykit_cells: {iteasykit_entity_type_id: mid}).each do |rel|
        cell = rel.iteasykit_cell
        yield(cell)
      end
    end

  end
end

iteasykit/app/controllers/iteasykit/admin/blocks_controller.rb
require_dependency "iteasykit/application_controller"

module Iteasykit
  class Admin::BlocksController < Admin::AdminController
    before_action :set_block, only: [:show, :edit, :update, :destroy, :custom_fields]

    # GET /blocks
    def index
      @block_entity_types = Iteasykit::EntityType.where(rel_model: 'Block')
      @blocks = Block.all
    end

    # GET /blocks/1
    def show
    end

    def custom_fields
      @fci = Iteasykit::Fci.new
      @fcis = Iteasykit::Fci.order(:position).where(fciable_id: @block.id, fciable_type: "Iteasykit::Block")
    end

    # GET /blocks/new
    def new
      @entity_type = Iteasykit::EntityType.find(params[:entity_type]) if params[:entity_type]
      @block = Block.new
    end

    # GET /blocks/1/edit
    def edit
      @object_list = @block.rel_cells.page params[:page]
    end

    # POST /blocks
    def create
      @block = Block.new(block_params)

      if @block.save
        fci_saver(@block, params)
        redirect_to edit_admin_block_url(@block), notice: 'Block was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /blocks/1
    def update
      if @block.update(block_params)
        fci_saver(@block, params)
        redirect_to edit_admin_block_url(@block), notice: 'Block was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /blocks/1
    def destroy
      @block.destroy
      redirect_to blocks_url, notice: 'Block was successfully destroyed.'
    end

    def sort
      params[:blocks].each do |key, value|
        Block.find(value[:id]).update_attributes(position: value[:position], region: value[:region])
      end
      render :nothing => true
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_block
        @block = Block.find(params[:id])
        @entity_type = @block.iteasykit_entity_type
      end

      # Only allow a trusted parameter "white list" through.
      def block_params
        params.require(:block).permit(:admin_name, :region, :type_url, :url, :etl_type, :entity_type_lists, :description_admin,
                                      :machine_name, :active, :position, :system, :iteasykit_entity_type_id, :elementcls, :idcls, :csscls)
      end
  end
end

iteasykit/app/helpers/iteasykit/blocks_helper.rb
module Iteasykit
  module BlocksHelper
    def region(region)
      @blocks = Block.where(region: region)
      render 'iteasykit/shared/blocks/list', locale: @blocks
    end

    def blocks_type(type)
      rt=Iteasykit::EntityType.includes(:translations).find_by_machine_name(type)
      Iteasykit::Block.where(iteasykit_entity_type_id: rt.id) unless rt.nil?
    end

    def block(name)
      @block = Iteasykit::Block.includes(:translations).find_by(machine_name: name)
      render 'iteasykit/shared/blocks/show', locale: @block
    end

    def geocod(d)
      Iteasykit::FciString.where(iteasykit_fci_id: d).where.not(value: '').map{|e|e.value+', '+e.fieldable_id.to_s}.map{|e| e.split(', ')}

    end

  def geocods(d)
    Rails.cache.fetch('helper_valuess') do
    @arrr =[]
    Iteasykit::FciString.where(iteasykit_fci_id: d).each do |string|
        @results = Geocoder.coordinates(string.value)
        unless @results.nil?
            @results << string.fieldable_id
            @arrr << @results
        end
    end
    @arrr
  end
end

  end
end

iteasykit/app/views/iteasykit/admin/blocks/_form.html.erb
<div class="row">
  <%= form_with(model: [:admin, block], local: true, multipart: true) do |form| %>
    <% if block.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(block.errors.count, "error") %> prohibited this entity from being saved:</h2>

        <ul>
          <% block.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="col-md-8">      <% if @entity_type %>
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('field_and_objects') %></h5>
        </div>

        <div class="content">

          <%= render 'iteasykit/shared/fields/field_list', locals: [@entity_type, @object = @block] %>

        </div>
      </div>
      <% end %>

      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('visible_block') %>:</h5>
        </div>

        <div class="content">

          <div class="form-group">
            <label class="control-label"><%= t('type_url') %></label>

            <%= form.select(:type_url, ['none', 'only', 'except'],
                            {include_blank: false}, class: "form-control input-sm input-warning") %>
            <span class="help-block"><small></small></span>
          </div>

          <div class="form-group">
            <label class="control-label"><%= t('url_list') %></label>
            <%= form.text_area :url, class: "form-control input-sm" %>
            <span class="help-block"><small></small></span>
          </div>

          <div class="form-group">
            <label class="control-label"><%= t('type_entity_type') %></label>
            <%= form.select(:etl_type, ['none', 'only', 'except'],
                            {include_blank: false}, class: "form-control input-sm input-warning") %>
            <span class="help-block"><small></small></span>
          </div>

          <div class="form-group">
            <label class="control-label"><%= t('entity_type_lists') %></label>
            <%= form.text_area :entity_type_lists, class: "form-control input-sm" %>
            <span class="help-block"><small></small></span>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('settings') %></h5>
        </div>

        <div class="content">

          <div class="form-group">
            <label class="control-label"><%= t('admin_name') %></label>
            <%= form.text_field :admin_name, class: "form-control input-sm" %>
            <span class="help-block"><small></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('admin_description') %></label>
            <%= form.text_area :description_admin, class: "form-control input-sm" %>
            <span class="help-block"><small></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('region') %></label>
            <%= form.select(:region, theme_setting['regions'].map {|et| [et[1], et[0]]},
                            {include_blank: true}, class: "form-control input-sm input-warning") %>
            <span class="help-block"><small></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('entity_type') %></label>
            <%= form.select(:iteasykit_entity_type_id, Iteasykit::EntityType.where(rel_model: 'Block').map {|et| [et.name, et.id]},
                            {include_blank: true}, class: "form-control input-sm input-warning") %>
            <span class="help-block"><small><%= t('no_edit') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('machine_name') %></label>
            <%= form.text_field :machine_name, class: "form-control input-sm" %>
            <span class="help-block"><small><%= t('machine_name_for_theme') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('position') %></label>
            <%= form.number_field :position, class: "form-control input-sm" %>
            <span class="help-block"><small></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('element') %></label>
            <%= form.text_field :elementcls, class: "form-control input-sm" %>
            <span class="help-block"><small></small></span>
          </div>
          <div class="form-group">
          <label class="control-label"><%= t('id') %></label>
          <%= form.text_field :idcls, class: "form-control input-sm" %>
          <span class="help-block"><small></small></span>
        </div>
          <div class="form-group">
            <label class="control-label"><%= t('class') %></label>
            <%= form.text_field :csscls, class: "form-control input-sm" %>
            <span class="help-block"><small></small></span>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label warning-color">
                  <%= t('active') %>
                  <%= form.check_box :active, class: "toggle toggle-success" %>
                  <i></i>
                </label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label warning-color">
                  <%= t('system') %>
                  <%= form.check_box :system, class: "toggle toggle-success" %>
                  <i></i>
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="actions"  style="position: fixed;bottom: 0px;right: 0px;" >
      <%= form.submit 'Save', class: "btn-success btn-lg"%>
    </div>
  <% end %>


</div>
<% if @entity_type.relation? %>
<% unless @object_list.nil? %>
  <div class="content-box">
    <div class="head head-border warning-color">
      <h5 class="content-title warning-color"><%= t('relation_cells') %></h5>
    </div>

    <div class="content">
      <% Iteasykit::EntityType.where(rel_model: 'Cell').each do |cet| %>
        <%= link_to "New "+cet.name, "", class: "btn btn-info waves-effect",
                    'data-toggle'=>"modal", 'data-target'=>"#modal-largenew#{cet.id}" %>
        <div class="modal fade" id="modal-largenew<%=cet.id %>" role="dialog" aria-hidden="true">
          <%= render 'iteasykit/admin/cells/popup_form', locals: [@entity_type=cet, @cell = Iteasykit::Cell.new, @objectrel=@block] %>
        </div>
      <% end %>
<br>
<br>
      <%= render 'iteasykit/admin/cells/rel_list_objects', locals: [@object_list, ] %>
    </div>
  </div>
<% end %>
<% end %>

iteasykit/app/views/iteasykit/admin/blocks/_list_objects.html.erb
<table class="table table-bordered table-hover table-striped">
  <thead>
  <tr>
    <th><%= t('id') %></th>
    <th><%= t('admin_name') %></th>
    <th><%= t('machine_name') %></th>
    <th><%= t('description') %></th>
    <th><%= t('region') %></th>
    <th><%= t('active') %></th>
    <th><%= t('system') %></th>
    <th><%= t('action') %></th>
  </tr>
  </thead>

  <tbody>
  <% @object_list.each do |block| %>
    <tr>
      <td><%= block.id %></td>
      <td><%= block.admin_name %></td>
      <td><%= block.machine_name %></td>
      <td><%= block.description_admin %></td>
      <td><%= block.region %></td>
      <td><i class="zmdi zmdi-<%= block.active ? 'check' : 'close' %>"></i></td>
      <td><i class="zmdi zmdi-<%= block.system ? 'check' : 'close' %>"></i></td>
      <td class="text-center">
        <%= link_to '<i class="zmdi zmdi-edit"></i>'.html_safe, edit_admin_block_path(block), class: "btn btn-success raised icon waves-effect" %>
        <%= link_to '<i class="zmdi zmdi-delete"></i>'.html_safe, [:admin, block], class: "btn btn-danger raised icon waves-effect", method: :delete,
                    data: {confirm: 'Are you sure?'} %>     </td>

    </tr>
  <% end %>
  </tbody>
</table>

iteasykit/app/views/iteasykit/admin/blocks/custom_fields.html.erb
<% content_for :entity_title do %><%= t('fields_in_custom') %> <%= @block.machine_name %> entity
<% end %>
<% content_for :pull_right do %>
  <%= link_to '<i class="zmdi zmdi-long-arrow-return zmdi-hc-fw"></i>'.html_safe, admin_block_url(@block) %>
<% end %>

<ul class="nav nav-tabs text-right">
  <li>
    <a href="/admin/blocks/new/?entity_type=<%= @entity_type.id %>"><%= t('new') %> <%= @entity_type.name %></a>
  </li>
  <li>
    <a href="<%= edit_admin_block_path(@block) %>" ><%= t('edit_block') %></a>
  </li>
  <li class="active">
    <a href="<%= admin_block_custom_fields_path(@block) %>" ><%= t('custom_field') %> <%= @block.admin_name %></a>
  </li>
  <li>
    <a href="<%= admin_entity_type_url(@entity_type) %>"><%= t('list') %> <%= @entity_type.name %></a>
  </li>

  <li>
    <div class="btn-group no-bg">
      <button type="button" class="btn btn-no-bg warning-color dropdown-toggle waves-effect" data-toggle="dropdown" aria-expanded="false">
        <i class="zmdi zmdi-settings"></i>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a class="warning-color" href="<%= admin_blocks_url %>"><%= t('blocks_for_region') %></a></li>
        <li><a class="warning-color" href="<%= edit_admin_entity_type_url(@entity_type) %>"><%= t('edit_entity_type') %></a></li>
        <li><a class="warning-color" href="<%= admin_entity_type_fields_url(@entity_type) %>">Field entity type</a></li>

      </ul>
    </div></li>
</ul>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-8">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('list_field') %>
            <a class="fullscreen-btn" href="#"><i class="zmdi zmdi-fullscreen"></i></a></h5>


        </div>

        <div class="content">
          <table class="table table-bordered table-hover table-striped">
            <thead>
            <tr>
              <th><%= t('drop') %></th>
              <th><%= t('id') %></th>
              <th><%= t('name') %></th>
              <th><%= t('type') %></th>
              <th><%= t('machine_name') %></th>
              <th><%= t('help') %></th>

              <th><%= t('active') %></th>

              <th><%= t('action') %></th>
            </tr>
            </thead>
            <tbody class="sortable">  <!-- sortable target -->
            <% @fcis.each_with_sortable_id do |item, sortable_id| %>
              <tr id="<%= sortable_id %>">  <!-- Needs id tag on sorting elements -->
                <td><i class="zmdi zmdi-arrows zmdi-hc-fw"></i></td>
                <td><%= item.id %></td>
                <td><%= item.name %></td>
                <td><%= item.type_fci %></td>
                <td><%= item.machine_name %></td>
                <td><%= item.help %></td>
                <td><i class="zmdi zmdi-<%= item.active ? 'check' : 'close' %>"></i></td>

                <td class="text-center">
                  <%= link_to '<i class="zmdi zmdi-edit"></i>'.html_safe, "", class: "btn btn-success raised icon waves-effect",
                              'data-toggle'=>"modal", 'data-target'=>"#modal-large#{item.id}" %>
                  <%= link_to '<i class="zmdi zmdi-delete"></i>'.html_safe, [:admin, item], class: "btn btn-danger raised icon waves-effect", method: :delete,
                              data: {confirm: 'Are you sure?'} %></td>
              </tr>
              <div class="modal fade" id="modal-large<%=item.id %>" role="dialog" aria-hidden="true">
                <%= render 'iteasykit/admin/fcis/edit_form', fci: item %>
              </div>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('add_new_field') %></h5>
        </div>

        <div class="content">
          <%= render 'iteasykit/admin/fcis/form', locals: [@fci, @type = "Iteasykit::Block", @id = @block.id] %>
        </div>
      </div>

    </div>
  </div>
</div>

iteasykit/app/views/iteasykit/admin/blocks/edit.html.erb
<% content_for :entity_title do %><%= t('editing') %> <%= @block.title %>
<% end %>
<% content_for :pull_right do %>
  <%= link_to '<i class="zmdi zmdi-long-arrow-return zmdi-hc-fw"></i>'.html_safe, admin_blocks_url %>
<% end %>
<%= render 'iteasykit/shared/admin/type_tabs', locals: [@obj_current = @block, @cfield = false, @only_id = true] %>
<%= render 'form', block: @block %>

iteasykit/app/views/iteasykit/admin/blocks/index.html.erb
<% content_for :entity_title do %><%= t('list_blocks') %>
<% end %>
<% @block_entity_types.each do |bet| %>
  <a href="/admin/blocks/new/?entity_type=<%= bet.id %>" class="btn btn-info btn-sm" style='color: white!important;'>
    <%= t('new') %> <%= bet.name %>
  </a>
<% end %>
<br><br>
<div id="row">
  <% theme_setting['regions'].each do |region, details| %>

    <div class="content-box">
      <div class="head head-border danger-color">
        <h5 class="content-title danger-color"> <%= t('region_theme') %> - <%= details %></h5>
      </div>

      <div class="content">
    <ul data-id="<%= region.downcase %>" id="sortable-head" class="sortable-block">
      <li class="clearfix header dontsortme no-nest">
        <div class="listitem-drag">
          <i class="zmdi zmdi-arrows zmdi-hc-fw"></i>
        </div>
        <div class="listitem-name" style="width:80%;">
          <%= t('block_info') %>
        </div>
        <div class="listitem-action" style="width:15%;">
          <%= t(:action) %>
        </div>
      </li>
    </ul>
    <ul data-id="<%= region.downcase %>" class="sortable-block">
      <% @blocks.where(region: region).each do |block| %>
        <li data-id="<%= block.id %>" class="no-nest">
          <div class="listitem-drag handle"><i class="zmdi zmdi-arrows zmdi-hc-fw"></i></div>
          <div class="listitem-name" style="width:80%;">(<%= block.id %>) <b><%= block.admin_name %></b>
            - <%= block.iteasykit_entity_type.name unless block.iteasykit_entity_type.nil? %> - <%= block.machine_name %></div>
          <div class="listitem-action" style="width:15%;">
            <%= link_to ' ', edit_admin_block_path(block), class: 'glyphicon glyphicon-pencil' %>
            <%= link_to ' ', [:admin, block], method: :delete, data: {confirm: 'Are you sure?'}, class: 'glyphicon glyphicon-remove' %>
          </div>
        </li><br>
      <% end %>
    </ul>
    </br>
      </div>
    </div>
  <% end %>

  <div class="content-box">
    <div class="head head-border danger-color">
      <h5 class="content-title danger-color">   <%= t('not_activated') %></h5>
    </div>

    <div class="content">
  <ul id="sortable-head" class="sortable-block">
    <li class="clearfix header dontsortme no-nest">
      <div class="listitem-drag">
        <i class="zmdi zmdi-arrows zmdi-hc-fw" ></i>
      </div>
      <div class="listitem-name" style="width:80%;">
        <%= t('block_info') %>
      </div>
      <div class="listitem-action" style="width:15%;">
        <%= t(:action) %>
      </div>
    </li>
  </ul>
  <ul data-id="" class="sortable-block">
    <% @blocks.where("iteasykit_blocks.region = ? OR iteasykit_blocks.region = ?", '', 'undefined').each do |block| %>

      <li data-id="<%= block.id %>" class="no-nest">
        <div class="listitem-drag handle" ><i class="zmdi zmdi-arrows zmdi-hc-fw"></i></div>
        <div class="listitem-name" style="width:80%;">(<%= block.id %>) <b><%= block.admin_name %></b>
          - <%= block.iteasykit_entity_type.name unless block.iteasykit_entity_type.nil? %> - <%= block.machine_name %></div>
        <div class="listitem-action" style="width:15%;">
          <%= link_to ' ', edit_admin_block_path(block), class: 'glyphicon glyphicon-pencil' %>
          <%= link_to ' ', [:admin, block], method: :delete, data: {confirm: 'Are you sure?'}, class: 'glyphicon glyphicon-remove' %>
        </div>
      </li>
    <% end %>
  </ul>
</div>
  </div>
</div>

iteasykit/app/views/iteasykit/admin/blocks/new.html.erb
<% content_for :entity_title do %><%= t('new_block') %>
<% end %>
<% content_for :pull_right do %>
  <%= link_to '<i class="zmdi zmdi-long-arrow-return zmdi-hc-fw"></i>'.html_safe, admin_blocks_url %>
<% end %>
<%= render 'iteasykit/shared/admin/type_tabs', locals: [@obj_current = @block, @cfield = false, @only_id = true] %>
<%= render 'form', block: @block %>

iteasykit/app/views/iteasykit/admin/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin name:</strong>
  <%= @block.admin_name %>
</p>

<p>
  <strong>Region:</strong>
  <%= @block.region %>
</p>

<p>
  <strong>Type url:</strong>
  <%= @block.type_url %>
</p>

<p>
  <strong>Url:</strong>
  <%= @block.url %>
</p>

<p>
  <strong>Etl type:</strong>
  <%= @block.etl_type %>
</p>

<p>
  <strong>Entity type lists:</strong>
  <%= @block.entity_type_lists %>
</p>

<p>
  <strong>Description admin:</strong>
  <%= @block.description_admin %>
</p>

<p>
  <strong>Machine name:</strong>
  <%= @block.machine_name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @block.active %>
</p>

<p>
  <strong>Position:</strong>
  <%= @block.position %>
</p>

<p>
  <strong>System:</strong>
  <%= @block.system %>
</p>

<p>
  <strong>Iteasykit entity type:</strong>
  <%= @block.iteasykit_entity_type %>
</p>

<p>
  <strong>Elementcls:</strong>
  <%= @block.elementcls %>
</p>

<p>
  <strong>Idcls:</strong>
  <%= @block.idcls %>
</p>

<p>
  <strong>Csscls:</strong>
  <%= @block.csscls %>
</p>

<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', blocks_path %>