iteasykit/config/routes.rb
Iteasykit::Engine.routes.draw do

  #filter :pagination, :uuid
  filter :locale
  mount Ckeditor::Engine => '/ckeditor'
  resources :forms
  root :to => 'entities#index'
  resources :taxonomies
  resources :entities
  devise_for :users, class_name: "Iteasykit::User", module: :devise, :controllers => { :registrations => :registrations }
  namespace :admin do
    resources :taxonomies
    resources :fcis
    resources :entities
    resources :seomores
    resources :forms
    resources :cells
    resources :menus
    resources :menu_items do
      post :sort, on: :collection
    end
    resources :blocks do
      post :sort, on: :collection
    end
    resources :entity_types

  end
  resources :fci_images
  get 'admin/dashboard' => 'admin/page#dashboard', as: 'admin_dashboard'
  get 'admin/help' => 'admin/page#help', as: 'admin_help'
  get 'admin/entity_types/:id/fields' => 'admin/entity_types#fields', as: 'admin_entity_type_fields'
  get 'admin/entity/:id/custom_fields' => 'admin/entities#custom_fields', as: 'admin_entity_custom_fields'
  get 'admin/blocks/:id/custom_fields' => 'admin/blocks#custom_fields', as: 'admin_block_custom_fields'
  get 'admin/taxonomy/:id/custom_fields' => 'admin/taxonomies#custom_fields', as: 'admin_taxonomy_custom_fields'
  get 'admin/fcis/:id/destroy_fields' => 'admin/fcis#destroy_fields', as: 'admin_fci_destroy_fields'


  Iteasykit::DynamicRouter.load
  

end

iteasykit/app/models/iteasykit/entity.rb
module Iteasykit
  class Entity < ApplicationRecord
    translates :slug
    extend FriendlyId
    friendly_id :slug, :use => [:slugged, :finders, :globalize, :history]
    belongs_to :iteasykit_entity_type, class_name: "Iteasykit::EntityType"
    belongs_to :iteasykit_seomore, optional: true, class_name: "Iteasykit::Seomore", dependent: :destroy
    has_many :fcis, as: :fciable
    has_many :rel_cells, as: :relable, class_name: "Iteasykit::RelCell", foreign_key: :relable_id, dependent: :destroy
    has_many :iteasykit_cells, through: :rel_cells
    has_many :rel_taxonomies, as: :relable, class_name: "Iteasykit::RelTaxonomy", foreign_key: :relable_id, dependent: :destroy
    accepts_nested_attributes_for   :iteasykit_seomore

    after_save :translit

    def translit
      if slug.blank?
        if self.title.present?
          @translit = I18n.transliterate(self.title)
          update(slug: @translit.parameterize(separator: "_")+id.to_s)
        else
          update(slug: self.id)
        end
      end
    end

    def field(name)
      fci = Iteasykit::Fci.find_by_machine_name(name)
      if fci
        m = ('Iteasykit::Fci'+fci.type_fci.camelize).constantize
        if fci.is_multi?
          mf = m.where(iteasykit_fci_id: fci.id, fieldable_type: 'Iteasykit::Entity', fieldable_id: id)
          if mf
            if m.class_name == "IteasykitFciImage"
              mf.map{|f| f.file}.compact
            else
              if mf.value.class == Integer
                mfv = mf.value
              else
                mfv = mf.value.html_safe
              end
            end
          end
        else
          mf = m.find_by(iteasykit_fci_id: fci.id, fieldable_type: 'Iteasykit::Entity', fieldable_id: id)
          if mf
            if m.class_name == "IteasykitFciImage"
              mf.file
            else
              if mf.value.class == Integer
                mfv = mf.value
              else
                mfv = mf.value.html_safe
              end
            end
          end
        end
      end
    end

    def field_name(name)
      fci = Iteasykit::Fci.find_by_machine_name(name)
      fci.name.html_safe if fci
    end

    def title
      if iteasykit_entity_type.present?
        if iteasykit_entity_type.id_title_fci.present?
          fci = Iteasykit::Fci.find(iteasykit_entity_type.id_title_fci)
          mf = FciString.find_by(iteasykit_fci_id: fci.id, fieldable_type: 'Iteasykit::Entity', fieldable_id: id)
          if mf
            mf.value.html_safe
          end
        end
      end
    end

    def cells(mid)
      rel_cells.joins(:iteasykit_cell).where(iteasykit_cells: {iteasykit_entity_type_id: mid}).each do |rel|
				cell = rel.iteasykit_cell
        yield(cell)
      end
    end


  end
end

iteasykit/app/models/iteasykit/entity_type.rb
module Iteasykit
  class EntityType < ApplicationRecord
    has_many :iteasykit_entities, class_name: "Iteasykit::Entity", foreign_key: :iteasykit_entity_type_id
    has_many :iteasykit_cells, class_name: "Iteasykit::Cell", foreign_key: :iteasykit_entity_type_id
    has_many :fcis, as: :fciable
    translates :name, :description, :help
    before_save :translit

    def translit
      if self.machine_name.blank?
        @translit = name
        self.machine_name = @translit.parameterize(separator: "_")
      end
    end
  end
end

iteasykit/app/controllers/iteasykit/admin/entities_controller.rb
require_dependency "iteasykit/application_controller"

module Iteasykit
  class Admin::EntitiesController < Admin::AdminController
    before_action :set_entity, only: [:show, :edit, :update, :destroy, :custom_fields]

    # GET /entities
    def index
      @entities = Entity.all
    end

    # GET /entities/1
    def show

    end

    def custom_fields
      @fci = Iteasykit::Fci.new
      @fcis = Iteasykit::Fci.order(:position).where(fciable_id: @entity.id, fciable_type: "Iteasykit::Entity")
    end

    # GET /entities/new
    def new
      @entity_type = Iteasykit::EntityType.find(params[:entity_type])
      @entity = Entity.new
      @entity.build_iteasykit_seomore
    end

    # GET /entities/1/edit
    def edit
      @object_list = @entity.rel_cells.page params[:page]
      @entity.build_iteasykit_seomore if @entity.iteasykit_seomore.nil?
    end

    # POST /entities
    def create
      @entity = Entity.new(entity_params)

      if @entity.save
        fci_saver(@entity, params)

        redirect_to edit_admin_entity_url(@entity), notice: 'Entity was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /entities/1
    def update
      if @entity.update(entity_params)
        fci_saver(@entity, params)

        redirect_to edit_admin_entity_url(@entity), notice: 'Entity was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /entities/1
    def destroy
      @entity_type = @entity.iteasykit_entity_type
      @entity.destroy
      redirect_to admin_entity_type_url(@entity_type), notice: 'Entity was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.friendly.find(params[:id])
      @entity_type = @entity.iteasykit_entity_type
    end

    # Only allow a trusted parameter "white list" through.
    def entity_params
      params.require(:entity).permit(:machine_name, :iteasykit_entity_type_id, :active, :sticky, :iteasykit_seomore_id,
                                     :slug, :created_at, iteasykit_seomore_attributes: [:id, :noindex, :nofollow, :title, :keywords,
                                                                           :description, :canonical, :author, :publisher,
                                                                           :alternate, :refresh])
    end
  end
end

iteasykit/app/controllers/iteasykit/entities_controller.rb
require_dependency "iteasykit/application_controller"

module Iteasykit
  class EntitiesController < ApplicationController
    before_action :set_entity, only: [:show, :edit, :update, :destroy]

    # GET /entities
    def index
      @entities = Entity.all
      @global_search = Iteasykit::FciString.where(fieldable_type: 'Iteasykit::Entity').ransack(params[:q])
      @global_search2 = Iteasykit::FciText.where(fieldable_type: 'Iteasykit::Entity').ransack(params[:q])
      if params[:q].present?
        @qq = @global_search.result + @global_search2.result
      else
        @qq = @global_search.result
      end
      @lists = @qq.uniq
    end

    # GET /entities/1
    def show
      @global_search = Iteasykit::FciString.where(fieldable_type: 'Iteasykit::Entity').ransack(params[:q])
      @global_search2 = Iteasykit::FciText.where(fieldable_type: 'Iteasykit::Entity').ransack(params[:q])
      if params[:q].present?
        @qq = @global_search.result + @global_search2.result
      else
        @qq = @global_search.result
      end
      @lists = @qq.uniq { |p| p.fieldable_id }
    end

    # GET /entities/new
    def new
      @entity = Entity.new
    end

    # GET /entities/1/edit
    def edit
    end

    # POST /entities
    def create
      @entity = Entity.new(entity_params)

      if @entity.save
        redirect_to @entity, notice: 'Entity was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /entities/1
    def update
      if @entity.update(entity_params)
        redirect_to @entity, notice: 'Entity was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /entities/1
    def destroy
      @entity.destroy
      redirect_to entities_url, notice: 'Entity was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_entity
        @entity = Entity.friendly.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def entity_params
        params.require(:entity).permit(:machine_name, :iteasykit_entity_type_id, :active, :sticky, :iteasykit_seomore_id)
      end
  end
end

iteasykit/app/helpers/iteasykit/entities_helper.rb
module Iteasykit
  module EntitiesHelper
  end
end

iteasykit/app/views/iteasykit/admin/entities/_form.html.erb
<div class="row">
  <%= form_with(model: [:admin, entity], local: true, multipart: true) do |form| %>
    <% if entity.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

        <ul>
          <% entity.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="col-md-8">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('field_and_objects') %></h5>
        </div>

        <div class="content">
          <%= render 'iteasykit/shared/fields/field_list', locals: [@entity_type, @object = @entity] %>

        </div>
      </div>


      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('SEO') %></h5>
        </div>

        <div class="content">

          <%= render 'iteasykit/admin/seomores/form', form: form %>
        </div>
      </div>

    </div>


    <div class="col-md-4">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('settings') %></h5>
        </div>

        <div class="content">

          <div class="form-group">
            <label class="control-label"><%= t('url') %></label>
            <%= form.text_field :slug, class: "form-control input-sm" %>
            <span class="help-block"><small><%= t('no_edit') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('entity_type') %></label>
            <%= form.select(:iteasykit_entity_type_id, Iteasykit::EntityType.where(rel_model: 'Entity').map {|et| [et.name, et.id]},
                            {include_blank: false}, class: "form-control input-sm input-warning") %>
            <span class="help-block"><small><%= t('no_edit') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('machine_name') %></label>
            <%= form.text_field :machine_name, class: "form-control input-sm" %>
            <span class="help-block"><small><%= t('machine_name_for_theme') %></small></span>
          </div>
          <div class="form-group">
            <label class="control-label">Date</label>
            <%= form.date_field :created_at, class: "form-control input-sm" %>
            <span class="help-block"><small></small></span>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label warning-color">
                  <%= t('active') %>
                  <%= form.check_box :active, class: "toggle toggle-success" %>
                  <i></i>
                </label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label warning-color">

                  <%= t('sticky') %>
                  <%= form.check_box :sticky, class: "toggle toggle-success" %>
                  <i></i>
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>

      <% taxonomies = Iteasykit::Taxonomy.all %>
      <% if taxonomies.present? %>
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('category_taxonomy') %></h5>
        </div>

        <div class="content">
          <%= link_to t('set_category'), "", class: "btn btn-success waves-effect",
                                                 'data-toggle'=>"modal", 'data-target'=>"#modal-largecat" %>
          <div class="modal fade" id="modal-largecat" role="dialog" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><%= t('all_category') %></h4>
              </div>
                <div class="modal-body">
                  <% taxonomies.group_by {|t| t.iteasykit_entity_type.name }.each do |name, taxs| %>
                    <h3><%= name %></h3>

                    <table class="table table-bordered table-hover table-striped">
                      <thead>
                      <tr>
                        <th><%= t('title') %></th>
                        <th><%= t('action') %></th>
                      </tr>
                      </thead>

                      <tbody>
                      <% taxs.each do |taxonomy| %>
                        <tr>
                          <td><%= taxonomy.title %></td>
                          <td class="text-center">
                            <%= link_to "set", "/admin/taxonomies/#{taxonomy.id}?reltaxentity=#{@entity.id}&reltaxtype=Iteasykit::Entity" %>
                           </td>
                        </tr>
                      <% end %>

                      </tbody>
                    </table>
                  <% end %>
                </div>
            </div>
          </div>
          </div>
          <br>
          <br>
          <table class="table table-bordered table-hover table-striped">
            <thead>
            <tr>
              <th><%= t('title') %></th>
              <th><%= t('action') %></th>
            </tr>
            </thead>

            <tbody>
            <% @entity.rel_taxonomies.each do |rel| %>
            <% taxonomy = rel.iteasykit_taxonomy %>
              <tr>
                <td><%= taxonomy.title %></td>
                <td class="text-center">
                  <%= link_to "destroy", "/admin/taxonomies/#{taxonomy.id}?delreltaxentity=#{@entity.id}&reltaxtype=Iteasykit::Entity" %>
                </td>
              </tr>
            <% end %>

            </tbody>
          </table>

        </div>
        </div>
      </div>
    <% end %>

    </div>
      <div class="actions"  style="position: fixed;bottom: 0px;right: 0px;" >
        <%= form.submit t('save'), class: "btn-success btn-lg"%>
      </div>
  <% end %>
  </div>

  <% if @entity_type.relation? %>
    <% unless @object_list.nil? %>
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('relation_cells') %></h5>
        </div>

        <div class="content">
          <% Iteasykit::EntityType.where(rel_model: 'Cell').each do |cet| %>
            <%= link_to "+ "+cet.name, "", class: "btn btn-info waves-effect",
                        'data-toggle'=>"modal", 'data-target'=>"#modal-largenew#{cet.id}" %>
            <div class="modal fade" id="modal-largenew<%=cet.id %>" role="dialog" aria-hidden="true">
              <%= render 'iteasykit/admin/cells/popup_form', locals: [@entity_type=cet, @cell = Iteasykit::Cell.new, @objectrel=@entity] %>
            </div>
          <% end %>
          <br>
          <br>
          <%= render 'iteasykit/admin/cells/rel_list_objects', locals: [@object_list, ] %>
        </div>
      </div>
    <% end %>
  <% end %>

iteasykit/app/views/iteasykit/admin/entities/_list_objects.html.erb
  <p><%= t(:help_list_entity) %></p>

<table class="table table-bordered table-hover table-striped">
  <thead>
  <tr>
    <th><%= t('id') %></th>
    <th><%= t('title') %></th>
    <th><%= t('machine_name') %></th>
    <th><%= t('active') %></th>
    <th><%= t('sticky') %></th>
    <th><%= t('action') %></th>
  </tr>
  </thead>

  <tbody>
  <% @object_list.each do |entity| %>
    <tr>
      <td><%= entity.id %></td>
      <td><%= entity.title %></td>
      <td><%= entity.machine_name %></td>
      <td><i class="zmdi zmdi-<%= entity.active ? 'check' : 'close' %>"></i></td>
      <td><i class="zmdi zmdi-<%= entity.sticky ? 'check' : 'close' %>"></i></td>
      <td class="text-center">

        <%= link_to '<i class="zmdi zmdi-edit"></i>'.html_safe, edit_admin_entity_path(entity), class: "btn btn-success raised icon waves-effect" %>
        <%= link_to '<i class="zmdi zmdi-delete"></i>'.html_safe, [:admin, entity], class: "btn btn-danger raised icon waves-effect", method: :delete,
                    data: {confirm: 'Are you sure?'} %>     </td>

    </tr>
  <% end %>
  </tbody>
</table>

iteasykit/app/views/iteasykit/admin/entities/custom_fields.html.erb
<% content_for :entity_title do %><%= t('fields_in_custom') %> - <%= @entity.title %>
<% end %>
<% content_for :pull_right do %>
  <%= link_to '<i class="zmdi zmdi-long-arrow-return zmdi-hc-fw"></i>'.html_safe, admin_entity_url(@entity) %>
<% end %>

<%= render 'iteasykit/shared/admin/type_tabs', locals: [@obj_current = @entity] %>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-8">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('list_field') %>
            <a class="fullscreen-btn" href="#"><i class="zmdi zmdi-fullscreen"></i></a></h5>


        </div>

        <div class="content">
          <table class="table table-bordered table-hover table-striped">
            <thead>
            <tr>
              <th><%= t('drop') %></th>
              <th><%= t('id') %></th>
              <th><%= t('name') %></th>
              <th><%= t('type') %></th>
              <th><%= t('machine_name') %></th>
              <th><%= t('help') %></th>

              <th><%= t('active') %></th>

              <th><%= t('action') %></th>
            </tr>
            </thead>
            <tbody class="sortable">  <!-- sortable target -->
            <% @fcis.each_with_sortable_id do |item, sortable_id| %>
              <tr id="<%= sortable_id %>">  <!-- Needs id tag on sorting elements -->
                <td><i class="zmdi zmdi-arrows zmdi-hc-fw"></i></td>
                <td><%= item.id %></td>
                <td><%= item.name %></td>
                <td><%= item.type_fci %></td>
                <td><%= item.machine_name %></td>
                <td><%= item.help %></td>
                <td><i class="zmdi zmdi-<%= item.active ? 'check' : 'close' %>"></i></td>
                <td class="text-center">
                  <%= link_to '<i class="zmdi zmdi-edit"></i>'.html_safe, "", class: "btn btn-success raised icon waves-effect",
                              'data-toggle'=>"modal", 'data-target'=>"#modal-large#{item.id}" %>
                  <%= link_to '<i class="zmdi zmdi-delete"></i>'.html_safe, [:admin, item], class: "btn btn-danger raised icon waves-effect", method: :delete,
                              data: {confirm: 'Are you sure?'} %></td>
              </tr>
              <div class="modal fade" id="modal-large<%=item.id %>" role="dialog" aria-hidden="true">
                <%= render 'iteasykit/admin/fcis/edit_form', fci: item %>
              </div>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="content-box">
        <div class="head head-border warning-color">
          <h5 class="content-title warning-color"><%= t('add_new_field') %></h5>
        </div>

        <div class="content">
              <%= render 'iteasykit/admin/fcis/form', locals: [@fci, @type = "Iteasykit::Entity", @id = @entity.id] %>
        </div>
      </div>

    </div>
  </div>
</div>

iteasykit/app/views/iteasykit/admin/entities/edit.html.erb
<% content_for :entity_title do %><%= t('editing') %>  <%= @entity_type.name %> - <%= @entity.title %>
<% end %>
<% content_for :pull_right do %>
  <%= link_to '<i class="zmdi zmdi-long-arrow-return zmdi-hc-fw"></i>'.html_safe, admin_entity_type_url(@entity_type) %>
<% end %>
<%= render 'iteasykit/shared/admin/type_tabs', locals: [@obj_current = @entity] %>
<%= render 'form', entity: @entity %>

iteasykit/app/views/iteasykit/admin/entities/index.html.erb
<% content_for :entity_title do %>List all entities
<% end %>
<% content_for :pull_right do %>

<% end %>


<table class="table table-bordered table-hover table-striped">
  <thead>
  <tr>
    <th>Machine name</th>
    <th>Entity type</th>
    <th>Active</th>
    <th>Sticky</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% @entities.each do |entity| %>
    <tr>
      <td><%= entity.machine_name %></td>
      <td><%= entity.iteasykit_entity_type.name %></td>
      <td><i class="zmdi zmdi-<%= entity.active ? 'check' : 'close' %>"></i></td>
      <td><i class="zmdi zmdi-<%= entity.sticky ? 'check' : 'close' %>"></i></td>
      <td class="text-center">
        <%= link_to '<i class="zmdi zmdi-edit"></i>'.html_safe, edit_admin_entity_path(entity), class: "btn btn-success raised icon waves-effect" %>
        <%= link_to '<i class="zmdi zmdi-delete"></i>'.html_safe, [:admin, entity], class: "btn btn-danger raised icon waves-effect", method: :delete,
                    data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path, class: "btn btn-success btn-lg", style: 'color: white!important;' %>

iteasykit/app/views/iteasykit/admin/entities/new.html.erb
<% content_for :entity_title do %><%= t('add_new') %> <%= @entity_type.name %>
<% end %>
<% content_for :pull_right do %>
  <%= link_to '<i class="zmdi zmdi-long-arrow-return zmdi-hc-fw"></i>'.html_safe, admin_entity_type_url(@entity_type) %>
<% end %>
<%= render 'iteasykit/shared/admin/type_tabs', locals: [@obj_current = @entity] %>
<p><%= t(:add_new_object) %></p>
<%= render 'form', entity: @entity %>

iteasykit/app/views/iteasykit/admin/entities/show.html.erb
<% if @entity.machine_name.nil? %>
  hello!!!
<% else %>
  <%= render @entity.machine_name %>
<% end %>